sports: "https://en.wikipedia.org/wiki/Major_professional_sports_teams_of_the_United_States_and_Canada"

area: "https://docs.google.com/uc?export=download&id=0B9YAGU9c9zmKV1ZNZFEza2tiSzQ"

roads: "https://docs.google.com/uc?export=download&id=0B9YAGU9c9zmKWWstVUJZVTBOOTA"

names:
  - "http://names.mongabay.com/most_common_surnames.htm"
  - "http://names.mongabay.com/most_common_surnames1.htm"
  - "http://names.mongabay.com/most_common_surnames2.htm"
  - "http://names.mongabay.com/most_common_surnames5.htm"
  - "http://names.mongabay.com/most_common_surnames8.htm"
  - "http://names.mongabay.com/male_names.htm"
  - "http://names.mongabay.com/male_names3.htm"
  - "http://names.mongabay.com/male_names6.htm"
  - "http://names.mongabay.com/male_names9.htm"
  - "http://names.mongabay.com/female_names.htm"
  - "http://names.mongabay.com/female_names1.htm"

babynames:
  - "http://names.mongabay.com/baby_names/boys-2014.html"
  - "http://names.mongabay.com/baby_names/boys500.html"
  - "http://names.mongabay.com/baby_names/boys750.html"
  - "http://names.mongabay.com/baby_names/boys1000.html"
  - "http://names.mongabay.com/baby_names/girls-2014.html"
  - "http://names.mongabay.com/baby_names/girls500.html"
  - "http://names.mongabay.com/baby_names/girls750.html"
  - "http://names.mongabay.com/baby_names/girls1000.html"

default: &default
  cities: "https://en.wikipedia.org/wiki/List_of_cities_in_%{state}"
  colleges: "https://en.wikipedia.org/wiki/List_of_college_athletic_programs_in_%{state}"
  landmarks: "https://en.wikipedia.org/wiki/List_of_National_Historic_Landmarks_in_%{state}"
  zip: "http://www.zipcodestogo.com/%{state}/"

states:
  alabama: &Alabama
    <<: *default
    abbrev: "AL"
    title: "Alabama"
  al: *Alabama

  alaska: &Alaska
    <<: *default
    abbrev: "AK"
    title: "Alaska"
  ak: *Alaska

  arizona: &Arizona
    <<: *default
    abbrev: "AZ"
    title: "Arizona"
  az: *Arizona

  arkansas: &Arkansas
    <<: *default
    abbrev: "AR"
    title: "Arkansas"
  ar: *Arkansas

  california: &California
    <<: *default
    abbrev: "CA"
    title: "California"
  ca: *California

  colorado: &Colorado
    <<: *default
    abbrev: "CO"
    title: "Colorado"
  co: *Colorado

  connecticut: &Connecticut
    <<: *default
    abbrev: "CT"
    title: "Connecticut"
  ct: *Connecticut

  delaware: &Delaware
    <<: *default
    abbrev: "DE"
    title: "Delaware"
  de: *Delaware

  district%20of%20columbia: &DistrictofColumbia
    <<: *default
    abbrev: "DC"
    cities: "https://en.wikipedia.org/wiki/Neighborhoods_in_Washington,_D.C."
    colleges: "https://en.wikipedia.org/wiki/List_of_college_athletic_programs_in_Washington,_D.C."
    landmarks: "https://en.wikipedia.org/wiki/List_of_National_Historic_Landmarks_in_Washington,_D.C."
    title: "District of Columbia"
  dc: *DistrictofColumbia

  florida: &Florida
    <<: *default
    abbrev: "FL"
    title: "Florida"
  fl: *Florida

  georgia: &Georgia
    <<: *default
    abbrev: "GA"
    colleges: "https://en.wikipedia.org/wiki/List_of_college_athletic_programs_in_Georgia_(U.S._state)"
    cities: "https://en.wikipedia.org/wiki/List_of_municipalities_in_Georgia_(U.S._state)"
    title: "Georgia"
  ga: *Georgia

  hawaii: &Hawaii
    <<: *default
    abbrev: "HI"
    title: "Hawaii"
  hi: *Hawaii

  idaho: &Idaho
    <<: *default
    abbrev: "ID"
    title: "Idaho"
  id: *Idaho

  illinois: &Illinois
    <<: *default
    abbrev: "IL"
    title: "Illinois"
  il: *Illinois

  indiana: &Indiana
    <<: *default
    abbrev: "IN"
    title: "Indiana"
  in: *Indiana

  iowa: &Iowa
    <<: *default
    abbrev: "IA"
    title: "Iowa"
  ia: *Iowa

  kansas: &Kansas
    <<: *default
    abbrev: "KS"
    title: "Kansas"
  ks: *Kansas

  kentucky: &Kentucky
    <<: *default
    abbrev: "KY"
    title: "Kentucky"
  ky: *Kentucky

  louisiana: &Louisiana
    <<: *default
    abbrev: "LA"
    title: "Louisiana"
  la: *Louisiana

  maine: &Maine
    <<: *default
    abbrev: "ME"
    title: "Maine"
  me: *Maine

  maryland: &Maryland
    <<: *default
    abbrev: "MD"
    title: "Maryland"
  md: *Maryland

  massachusetts: &Massachusetts
    <<: *default
    abbrev: "MA"
    title: "Massachusetts"
  ma: *Massachusetts

  michigan: &Michigan
    <<: *default
    abbrev: "MI"
    title: "Michigan"
  mi: *Michigan

  minnesota: &Minnesota
    <<: *default
    abbrev: "MN"
    title: "Minnesota"
  mn: *Minnesota

  mississippi: &Mississippi
    <<: *default
    abbrev: "MS"
    title: "Mississippi"
  ms: *Mississippi

  missouri: &Missouri
    <<: *default
    abbrev: "MO"
    title: "Missouri"
  mo: *Missouri

  montana: &Montana
    <<: *default
    abbrev: "MT"
    title: "Montana"
  mt: *Montana

  nebraska: &Nebraska
    <<: *default
    abbrev: "NE"
    title: "Nebraska"
  ne: *Nebraska

  nevada: &Nevada
    <<: *default
    abbrev: "NV"
    title: "Nevada"
  nv: *Nevada

  new%20hampshire: &NewHampshire
    <<: *default
    abbrev: "NH"
    title: "New Hampshire"
  nh: *NewHampshire

  new%20jersey: &NewJersey
    <<: *default
    abbrev: "NJ"
    title: "New Jersey"
  nj: *NewJersey

  new%20mexico: &NewMexico
    <<: *default
    abbrev: "NM"
    title: "New Mexico"
  nm: *NewMexico

  new%20york: &NewYork
    <<: *default
    abbrev: "NY"
    title: "New York"
  ny: *NewYork

  north%20carolina: &NorthCarolina
    <<: *default
    abbrev: "NC"
    title: "North Carolina"
  nc: *NorthCarolina

  north%20dakota: &NorthDakota
    <<: *default
    abbrev: "ND"
    title: "North Dakota"
  nd: *NorthDakota

  ohio: &Ohio
    <<: *default
    abbrev: "OH"
    title: "Ohio"
  oh: *Ohio

  oklahoma: &Oklahoma
    <<: *default
    abbrev: "OK"
    title: "Oklahoma"
  ok: *Oklahoma

  oregon: &Oregon
    <<: *default
    abbrev: "OR"
    title: "Oregon"
  or: *Oregon

  pennsylvania: &Pennsylvania
    <<: *default
    abbrev: "PA"
    title: "Pennsylvania"
  pa: *Pennsylvania

  rhode%20island: &RhodeIsland
    <<: *default
    abbrev: "RI"
    title: "Rhode Island"
  ri: *RhodeIsland

  south%20carolina: &SouthCarolina
    <<: *default
    abbrev: "SC"
    title: "South Carolina"
  sc: *SouthCarolina

  south%20dakota: &SouthDakota
    <<: *default
    abbrev: "SD"
    title: "South Dakota"
  sd: *SouthDakota

  tennessee: &Tennessee
    <<: *default
    abbrev: "TN"
    title: "Tennessee"
  tn: *Tennessee

  texas: &Texas
    <<: *default
    abbrev: "TX"
    title: "Texas"
  tx: *Texas

  utah: &Utah
    <<: *default
    abbrev: "UT"
    title: "Utah"
  ut: *Utah

  vermont: &Vermont
    <<: *default
    abbrev: "VT"
    title: "Vermont"
  vt: *Vermont

  virginia: &Virginia
    <<: *default
    abbrev: "VA"
    title: "Virginia"
  va: *Virginia

  washington: &Washington
    <<: *default
    abbrev: "WA"
    colleges: "https://en.wikipedia.org/wiki/List_of_college_athletic_programs_in_Washington_(state)"
    title: "Washington"
  wa: *Washington

  west%20virginia: &WestVirginia
    <<: *default
    abbrev: "WV"
    title: "West Virginia"
  wv: *WestVirginia

  wisconsin: &Wisconsin
    <<: *default
    abbrev: "WI"
    title: "Wisconsin"
  wi: *Wisconsin

  wyoming: &Wyoming
    <<: *default
    abbrev: "WY"
    title: "Wyoming"
  wy: *Wyoming
